spring.application.name=fsad-exam
spring.datasource.url=jdbc:mysql://localhost:3306/restaurantdb
spring.datasource.username=root
spring.datasource.password=Hansini@915

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8082